version: 2
jobs:
  build:
    working_directory: ~/browscapy
    docker:
      - image: cemsbr/python
    steps:
      - run:
          name: Cloning Repository
          command: cd .. && git clone --depth 1 git://github.com/cemsbr/browscapy.git
      - restore_cache:
          keys:
            - v2-installed-{{ checksum "requirements/dev.txt" }}
      - run:
          name: Installing Dependencies
          command: pip install --user -r requirements/dev.txt
      - save_cache:
          key: v2-installed-{{ checksum "requirements/dev.txt" }}
          paths:
            - ~/.cache
            - ~/.local
            - ~/browscapy/.tox
      - run:
          name: Test
          command: ~/.local/bin/tox
